name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64
          vs-prerelease: true
      - name: build release
        run:  msbuild msvc2022\ggml.sln -t:rebuild -verbosity:quiet -property:Configuration=Release
      - name: download
        run: |
          scripts\download.bat models\ggml-model-gpt-2-117M.bin https://github.com/leok7v/ggml/releases/download/2023-06-06/ggml-model-gpt-2-117M.bin
          scripts\download.bat models\ggml-model-stablelm-base-alpha-3b-q4_0.bin https://github.com/leok7v/ggml/releases/download/2023-06-06/ggml-model-stablelm-base-alpha-3b-q4_0.bin
      - name: test gpt-2
        run: |
          bin/Release/gpt-2.exe -m models\ggml-model-gpt-2-117M.bin -p "The best way to learn foreign language is" -n 256 -t 2
      - name: test neox
        run: |
          bin/Release/neox.exe  -m models\ggml-model-stablelm-base-alpha-3b-q4_0.bin -p "The best way to learn foreign language is" -n 256 -t 2
